# LeadLens Change Scanner - Auto-generated by Jentris
$projectPath = "C:\Projects\03-BusinessApps\leadlens"
$logPath = "$projectPath\change-log.txt"
$hoursBack = 24

# Get recent changes
$changes = Get-ChildItem -Path $projectPath -Recurse -File | 
    Where-Object {$_.LastWriteTime -gt (Get-Date).AddHours(-$hoursBack)} | 
    Select-Object @{Name="File";Expression={$_.FullName.Replace($projectPath, "")}}, LastWriteTime |
    Sort-Object LastWriteTime -Descending

# Format output
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$output = "=== LeadLens Scan - $timestamp ===`n"

if ($changes.Count -eq 0) {
    $output += "No files modified in last $hoursBack hours`n"
} else {
    $output += "Found $($changes.Count) modified files:`n"
    $changes | ForEach-Object { 
        $output += "  $($_.LastWriteTime.ToString('MM/dd HH:mm')) - $($_.File)`n" 
    }
}
$output += "`n" + "="*50 + "`n`n"

# Append to log
Add-Content -Path $logPath -Value $output -Encoding UTF8
Write-Host "Scan complete. Found $($changes.Count) changes."
