export const FEATURE_FLAGS = Object.freeze({
  SCAN_RECOVERY_ENABLED: true,
  SCAN_QUEUE_PROCESSING_ENABLED: true,
  OCR_IMAGE_OPTIMIZATION_ENABLED: true,
  SCAN_ENRICHMENT_QUEUE_ENABLED: true,
});

export const SCAN_RECOVERY_ENABLED = FEATURE_FLAGS.SCAN_RECOVERY_ENABLED;
export const SCAN_QUEUE_PROCESSING_ENABLED = FEATURE_FLAGS.SCAN_QUEUE_PROCESSING_ENABLED;
export const OCR_IMAGE_OPTIMIZATION_ENABLED = FEATURE_FLAGS.OCR_IMAGE_OPTIMIZATION_ENABLED;
export const SCAN_ENRICHMENT_QUEUE_ENABLED = FEATURE_FLAGS.SCAN_ENRICHMENT_QUEUE_ENABLED;

export default FEATURE_FLAGS;
